"""add_owner_to_salon

Revision ID: 70c3eba43154
Revises: 8f9dc718e31d
Create Date: 2026-05-11 20:49:42.988026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70c3eba43154'
down_revision: Union[str, None] = '8f9dc718e31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('reviews')
    op.drop_table('portfolio_photos')
    op.create_unique_constraint(None, 'salons', ['owner_id'])
    op.drop_constraint('users_managed_salon_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'portfolio_desc')
    op.drop_column('users', 'managed_salon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('managed_salon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('portfolio_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_managed_salon_id_fkey', 'users', 'salons', ['managed_salon_id'], ['id'])
    op.drop_constraint(None, 'salons', type_='unique')
    op.create_table('portfolio_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], name='portfolio_photos_master_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='portfolio_photos_pkey')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='reviews_booking_id_fkey'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='reviews_client_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('booking_id', name='reviews_booking_id_key')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], name='favorites_salon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'salon_id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
