"""add_timezone_to_salon

Revision ID: 87a16beb5ef0
Revises: 97d62390dfa1
Create Date: 2026-05-31 17:02:35.091285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a16beb5ef0'
down_revision: Union[str, None] = '97d62390dfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('timezone', sa.String(length=50), server_default='Europe/Moscow', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'timezone')
    # ### end Alembic commands ###
