"""add owner role and admin-salon link

Revision ID: 8f9dc718e31d
Revises: b8095981ecf9
Create Date: 2026-05-01 19:05:05.737034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9dc718e31d'
down_revision: Union[str, None] = 'b8095981ecf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salons', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('managed_salon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'salons', ['managed_salon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'managed_salon_id')
    op.drop_constraint(None, 'salons', type_='foreignkey')
    op.drop_column('salons', 'owner_id')
    # ### end Alembic commands ###
